-- MySQL Script generated by MySQL Workbench
-- Sat May  2 15:03:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `market` ;

-- -----------------------------------------------------
-- Table `market`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`authors` ;

CREATE TABLE IF NOT EXISTS `market`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `country` VARCHAR(30) NOT NULL DEFAULT 'Россия',
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `uq_authors_full_name` (`last_name` ASC, `first_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`books` ;

CREATE TABLE IF NOT EXISTS `market`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `genre` VARCHAR(30) NOT NULL DEFAULT 'проза',
  `price` DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `pages` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `publish_year` YEAR NULL DEFAULT NULL,
  `quantity` INT NOT NULL DEFAULT '100',
  PRIMARY KEY (`book_id`),
  INDEX `fk_books_author_id` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `market`.`authors` (`author_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`games` ;

CREATE TABLE IF NOT EXISTS `market`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` TEXT NOT NULL,
  `category` VARCHAR(80) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`cart` ;

CREATE TABLE IF NOT EXISTS `market`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `added_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `game_id` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_games`
    FOREIGN KEY (`game_id`)
    REFERENCES `market`.`games` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`customers` ;

CREATE TABLE IF NOT EXISTS `market`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `uq_customers_login` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`deleted_customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`deleted_customers` ;

CREATE TABLE IF NOT EXISTS `market`.`deleted_customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `deleted_at` DATETIME NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `uq_customers_login` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`logs` ;

CREATE TABLE IF NOT EXISTS `market`.`logs` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(50) NOT NULL,
  `operation_name` VARCHAR(20) NOT NULL,
  `operation_datetime` DATETIME NOT NULL,
  `current_user_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`orders` ;

CREATE TABLE IF NOT EXISTS `market`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `order_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `market`.`customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`order_items` ;

CREATE TABLE IF NOT EXISTS `market`.`order_items` (
  `order_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `quantity` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`order_id`, `book_id`),
  INDEX `fk_order_items_book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `market`.`books` (`book_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_items_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `market`.`orders` (`order_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `market`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `market`.`photos` ;

CREATE TABLE IF NOT EXISTS `market`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photos_games` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_photos_games`
    FOREIGN KEY (`game_id`)
    REFERENCES `market`.`games` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `market`;

DELIMITER $$

USE `market`$$
DROP TRIGGER IF EXISTS `market`.`books_after_delete` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`books_after_delete`
AFTER DELETE ON `market`.`books`
FOR EACH ROW
BEGIN
    INSERT INTO logs (table_name, operation_name, operation_datetime, current_user_name)
    VALUES ('books', 'delete', NOW(), CURRENT_USER());
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`books_before_insert` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`books_before_insert`
BEFORE INSERT ON `market`.`books`
FOR EACH ROW
BEGIN
    IF NEW.price > 5000 THEN
        SET NEW.price = 5000;
    END IF;
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`customers_after_delete` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`customers_after_delete`
AFTER DELETE ON `market`.`customers`
FOR EACH ROW
BEGIN
    INSERT INTO deleted_customers (customer_id, login, last_name, first_name, address, phone, deleted_at)
    VALUES (OLD.customer_id, OLD.login, OLD.last_name, OLD.first_name, OLD.address, OLD.phone, NOW());
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`customers_before_delete` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`customers_before_delete`
BEFORE DELETE ON `market`.`customers`
FOR EACH ROW
BEGIN
    DELETE FROM order_items
    WHERE order_id IN (
        SELECT order_id
        FROM orders
        WHERE customer_id = OLD.customer_id
    );

    DELETE FROM orders
    WHERE customer_id = OLD.customer_id;
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`orders_after_delete` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`orders_after_delete`
AFTER DELETE ON `market`.`orders`
FOR EACH ROW
BEGIN
    INSERT INTO logs (table_name, operation_name, operation_datetime, current_user_name)
    VALUES ('orders', 'delete', NOW(), CURRENT_USER());
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`orders_after_insert` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`orders_after_insert`
AFTER INSERT ON `market`.`orders`
FOR EACH ROW
BEGIN
    INSERT INTO logs (table_name, operation_name, operation_datetime, current_user_name)
    VALUES ('orders', 'insert', NOW(), CURRENT_USER());
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`orders_after_update` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`orders_after_update`
AFTER UPDATE ON `market`.`orders`
FOR EACH ROW
BEGIN
    INSERT INTO logs (table_name, operation_name, operation_datetime, current_user_name)
    VALUES ('orders', 'update', NOW(), CURRENT_USER());
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`orders_before_insert` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`orders_before_insert`
BEFORE INSERT ON `market`.`orders`
FOR EACH ROW
BEGIN
    SET NEW.order_datetime = NOW();
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`order_items_after_insert` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`order_items_after_insert`
AFTER INSERT ON `market`.`order_items`
FOR EACH ROW
BEGIN
    SELECT SUM(oi.quantity * b.price)
    INTO @orderCost
    FROM order_items AS oi
    INNER JOIN books AS b ON b.book_id = oi.book_id
    WHERE oi.order_id = NEW.order_id;
END$$


USE `market`$$
DROP TRIGGER IF EXISTS `market`.`order_items_before_insert` $$
USE `market`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `market`.`order_items_before_insert`
BEFORE INSERT ON `market`.`order_items`
FOR EACH ROW
BEGIN
    UPDATE books
    SET quantity = quantity - NEW.quantity
    WHERE book_id = NEW.book_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
